export const TANZANIA_REGIONS = [
  { name: "Arusha", code: "TZ.AS" },
  { name: "Dar es Salaam", code: "TZ.DS" },
  { name: "Dodoma", code: "TZ.DO" },
  { name: "Geita", code: "TZ.GE" },
  { name: "Iringa", code: "TZ.IG" },
  { name: "Kagera", code: "TZ.KG" },
  { name: "Katavi", code: "TZ.KA" },
  { name: "Kigoma", code: "TZ.KM" },
  { name: "Kilimanjaro", code: "TZ.KL" },
  { name: "Lindi", code: "TZ.LI" },
  { name: "Manyara", code: "TZ.MY" },
  { name: "Mara", code: "TZ.MA" },
  { name: "Mbeya", code: "TZ.MB" },
  { name: "Morogoro", code: "TZ.MO" },
  { name: "Mtwara", code: "TZ.MT" },
  { name: "Mwanza", code: "TZ.MZ" },
  { name: "Njombe", code: "TZ.NJ" },
  { name: "Pemba North", code: "TZ.PN" },
  { name: "Pemba South", code: "TZ.PS" },
  { name: "Pwani", code: "TZ.PW" },
  { name: "Rukwa", code: "TZ.RU" },
  { name: "Ruvuma", code: "TZ.RV" },
  { name: "Shinyanga", code: "TZ.SY" },
  { name: "Simiyu", code: "TZ.SI" },
  { name: "Singida", code: "TZ.SD" },
  { name: "Tabora", code: "TZ.TB" },
  { name: "Tanga", code: "TZ.TN" },
  { name: "Zanzibar North", code: "TZ.ZN" },
  { name: "Zanzibar South and Central", code: "TZ.ZS" },
  { name: "Zanzibar West", code: "TZ.ZW" },
];
